'use client'

import { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'ru'

const translations = {
  en: {
    // ... existing translations ...
    startNew: "Start a new Couple",
    or: "- OR -",
    enterCode: "Enter Invite Code",
    join: "Join",
    welcome: "Welcome to S&O",
    shareCode: "Share this code with your partner:",
    waiting: "Waiting for partner...",
    refresh: "Refresh",
    planMenu: "Weekly Menu",
    shoppingList: "Shopping List",
    addDishPlaceholder: "Dish name (e.g. Pasta)",
    add: "Add",
    noDishes: "No dishes yet. Add one!",
    selectDishesHint: "Select dishes in the Plan tab to generate a list.",
    openInTg: "Please open this app in Telegram",
    invalidCode: "Invalid code",
    failedJoin: "Failed to join",
    failedAdd: "Failed to add dish",
    invalidDishName: "Please enter a valid dish name (food-related only)",
    loading: "...",
    inviteCode: "Your Invite Code",
    delete: "Delete",
    close: "Close",
    shareLink: "Send to Partner",
    copied: "Copied!",
    generating: "Generating recipe...",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    addForDay: "Add for",
    ideas: "Ideas",
    settings: "Settings",
    sides: "Garnish / Carbs",
    proteins: "Proteins",
    veggies: "Vegetables",
    treats: "Treats / Fast Food",
    cuisines: "Cuisines",
    save: "Save",
    saving: "Saving...",
    generateIdeas: "Generate Ideas",
    noIdeas: "No ideas generated yet. Setup preferences and click Generate!",
    useIdea: "Use",
    // Options
    buckwheat: "Buckwheat",
    pasta: "Pasta",
    rice: "Rice",
    potato: "Potatoes",
    quinoa: "Quinoa",
    bulgur: "Bulgur",
    lentils: "Lentils",
    chicken: "Chicken",
    beef: "Beef",
    pork: "Pork",
    turkey: "Turkey",
    fish: "Fish",
    seafood: "Seafood",
    tomato: "Tomatoes",
    cucumber: "Cucumbers",
    pepper: "Bell Pepper",
    broccoli: "Broccoli",
    zucchini: "Zucchini",
    eggplant: "Eggplant",
    mushrooms: "Mushrooms",
    pizza: "Pizza",
    sushi: "Sushi",
    burger: "Burger",
    shawarma: "Shawarma",
    italian: "Italian",
    asian: "Asian",
    russian: "Russian",
    georgian: "Georgian",
    mexican: "Mexican",
    select: "Select",
    approve: "Approve",
    unapprove: "Unapprove",
    selectDay: "Select Day",
    copyLink: "Copy Link",
    logoutConfirm: "Are you sure you want to leave the couple? You will need to create or join a new couple.",
    categoryVegetables: "Vegetables",
    categoryFruits: "Fruits",
    categoryMeat: "Meat & Fish",
    categoryDairy: "Dairy",
    categoryBakery: "Bakery",
    categoryPantry: "Pantry",
    categorySpices: "Spices & Seasonings",
    categoryOther: "Other",
    search: "Search",
    sortBy: "Sort by",
    sortAlphabetical: "Alphabetical",
    sortCategory: "Category",
    sortAmount: "Amount",
    exportList: "Export List",
    exportAsText: "Export as Text",
    exportAsTelegram: "Send to Telegram",
    history: "History",
    saveWeek: "Save This Week",
    loadWeek: "Load Week",
    weekOf: "Week of",
    noHistory: "No saved weeks yet",
    savedWeeks: "Saved Weeks",
    deleteWeek: "Delete",
    deleteWeekConfirm: "Are you sure you want to delete this week?",
    addIngredient: "Add Ingredient",
    editIngredient: "Edit Ingredient",
    deleteIngredient: "Delete Ingredient",
    ingredientName: "Name",
    ingredientAmount: "Amount",
    ingredientUnit: "Unit",
    forDishes: "For dishes",
    manualIngredient: "Manual",
    addSuccess: "Added successfully",
    deleteSuccess: "Deleted successfully",
    updateIngredientSuccess: "Ingredient updated successfully",
    addIngredientSuccess: "Ingredient added successfully",
    deleteIngredientSuccess: "Ingredient deleted successfully",
    deleteDishConfirm: "Are you sure you want to delete this dish?",
    deleteIngredientConfirm: "Are you sure you want to delete this ingredient?",
    logout: "Logout",
    noResults: "No results found",
    toBuy: "To Buy",
    purchased: "Purchased",
    coupleSettings: "Couple Settings",
    useAIForIngredients: "Use AI to generate ingredients",
    useAIForIngredientsDesc: "Automatically generate ingredients and recipes for dishes using AI",
    settingsSaved: "Settings saved successfully",
    theme: "Theme",
    darkMode: "Dark",
    lightMode: "Light",
    today: "Today",
    tomorrow: "Tomorrow",
    yesterday: "Yesterday"
  },
  ru: {
    startNew: "Создать пару",
    or: "- ИЛИ -",
    enterCode: "Введите код приглашения",
    join: "Присоединиться",
    welcome: "Добро пожаловать в S&O",
    shareCode: "Отправьте этот код партнеру:",
    waiting: "Ждем партнера...",
    refresh: "Обновить",
    planMenu: "Меню на неделю",
    shoppingList: "Список покупок",
    addDishPlaceholder: "Название блюда (напр. Борщ)",
    add: "Добавить",
    noDishes: "Пока нет блюд. Добавьте что-нибудь!",
    selectDishesHint: "Выберите блюда во вкладке Меню, чтобы создать список.",
    openInTg: "Пожалуйста, откройте приложение в Telegram",
    invalidCode: "Неверный код",
    failedJoin: "Не удалось присоединиться",
    failedAdd: "Не удалось добавить блюдо",
    invalidDishName: "Пожалуйста, введите название блюда (только связанное с едой)",
    loading: "...",
    inviteCode: "Ваш код приглашения",
    delete: "Удалить",
    close: "Закрыть",
    shareLink: "Отправить партнеру",
    copyLink: "Скопировать ссылку",
    copied: "Скопировано!",
    logoutConfirm: "Вы уверены, что хотите выйти из пары? Вам нужно будет создать или присоединиться к новой паре.",
    categoryVegetables: "Овощи",
    categoryFruits: "Фрукты",
    categoryMeat: "Мясо и рыба",
    categoryDairy: "Молочные",
    categoryBakery: "Хлебобулочные",
    categoryPantry: "Бакалея",
    categorySpices: "Специи и приправы",
    categoryOther: "Прочее",
    search: "Поиск",
    sortBy: "Сортировать",
    sortAlphabetical: "По алфавиту",
    sortCategory: "По категории",
    sortAmount: "По количеству",
    exportList: "Экспорт списка",
    exportAsText: "Экспорт как текст",
    exportAsTelegram: "Отправить в Telegram",
    history: "История",
    saveWeek: "Сохранить неделю",
    loadWeek: "Загрузить неделю",
    weekOf: "Неделя с",
    noHistory: "Нет сохраненных недель",
    savedWeeks: "Сохраненные недели",
    deleteWeek: "Удалить",
    deleteWeekConfirm: "Вы уверены, что хотите удалить эту неделю?",
    addIngredient: "Добавить продукт",
    editIngredient: "Редактировать",
    deleteIngredient: "Удалить",
    ingredientName: "Название",
    ingredientAmount: "Количество",
    ingredientUnit: "Единица",
    forDishes: "Для блюд",
    manualIngredient: "Вручную",
    addSuccess: "Успешно добавлено",
    deleteSuccess: "Успешно удалено",
    updateIngredientSuccess: "Продукт успешно обновлен",
    addIngredientSuccess: "Продукт успешно добавлен",
    deleteIngredientSuccess: "Продукт успешно удален",
    deleteDishConfirm: "Вы уверены, что хотите удалить это блюдо?",
    deleteIngredientConfirm: "Вы уверены, что хотите удалить этот продукт?",
    logout: "Выйти",
    noResults: "Ничего не найдено",
    toBuy: "Нужно купить",
    purchased: "Куплено",
    coupleSettings: "Настройки пары",
    useAIForIngredients: "Использовать AI для генерации ингредиентов",
    useAIForIngredientsDesc: "Автоматически генерировать ингредиенты и рецепты для блюд с помощью AI",
    settingsSaved: "Настройки успешно сохранены",
    theme: "Тема",
    darkMode: "Темная",
    lightMode: "Светлая",
    today: "Сегодня",
    tomorrow: "Завтра",
    yesterday: "Вчера",
    generating: "Ищем ингредиенты...",
    days: ["Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота", "Воскресенье"],
    addForDay: "Добавить на",
    ideas: "Идеи",
    settings: "Настройки вкусов",
    sides: "Гарниры",
    proteins: "Мясо / Рыба",
    veggies: "Овощи",
    treats: "Вредное / Фастфуд",
    cuisines: "Кухня",
    save: "Сохранить",
    saving: "Сохранение...",
    generateIdeas: "Придумать что поесть",
    noIdeas: "Нет идей. Настройте предпочтения и нажмите кнопку!",
    useIdea: "Взять",
    // Options
    buckwheat: "Гречка",
    pasta: "Макароны",
    rice: "Рис",
    potato: "Картошка",
    quinoa: "Киноа",
    bulgur: "Булгур",
    lentils: "Чечевица",
    chicken: "Курица",
    beef: "Говядина",
    pork: "Свинина",
    turkey: "Индейка",
    fish: "Рыба",
    seafood: "Морепродукты",
    tomato: "Помидоры",
    cucumber: "Огурцы",
    pepper: "Перец",
    broccoli: "Брокколи",
    zucchini: "Кабачки",
    eggplant: "Баклажаны",
    mushrooms: "Грибы",
    pizza: "Пицца",
    sushi: "Суши / Роллы",
    burger: "Бургеры",
    shawarma: "Шаурма",
    italian: "Итальянская",
    asian: "Азиатская",
    russian: "Русская",
    georgian: "Грузинская",
    mexican: "Мексиканская",
    select: "Выбрать",
    approve: "Одобрить",
    unapprove: "Отменить одобрение",
    selectDay: "Выберите день"
  }
}

interface LanguageContextType {
  lang: Language
  setLang: (lang: Language) => void
  t: typeof translations['en']
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('ru') 

  useEffect(() => {
    // 1. Check localStorage
    const saved = localStorage.getItem('dft-lang') as Language
    if (saved && (saved === 'ru' || saved === 'en')) {
        setLangState(saved)
        return
    }

    // 2. Check Telegram
    if (typeof window !== 'undefined' && window.Telegram?.WebApp?.initDataUnsafe?.user?.language_code) {
        const tgLang = window.Telegram.WebApp.initDataUnsafe.user.language_code
        if (tgLang === 'ru' || tgLang.startsWith('ru-')) {
            setLangState('ru')
        } else {
            setLangState('en')
        }
    }
  }, [])

  const setLang = (l: Language) => {
      setLangState(l)
      localStorage.setItem('dft-lang', l)
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
